### PR TITLE
Updated OSSEC schema with tests

### PR DESCRIPTION
**Pull request by kostaspap**
### Background

Closes https://app.asana.com/0/1200124882238265/1200125013904170

### Changes

* Updated OSSEC schemas and removed `native` parser
* Moved sample events from Go unit tests. 

### Testing

```
./pantherlog-darwin-amd64 test schemas/logs/ossec/event_info.yml schemas/logs/ossec/event_info_tests.yml

```

### CODE REVIEW

**Comment by kostaspap** [comment]
@alxarch how does the structure look like?

**Comment by alxarch** [comment]
The schema seems right.
After merge on master we need to check the behavior of `mage schemas:pull`. It should be picking up the non-native parser.
The tests are not covering ips. We should get more samples, we might discover field name mistakes.

**Review by alxarch — APPROVED** [review]
LGTM

**Comment by alxarch** [comment]
Just a note, tests can be run on a dir also i.e.:
```
pantherlog test ./schemas/logs/ossec
```

**Pull request merged**
