### PR TITLE
GreyNoise AWS S3 Get/List Object

### PR DESCRIPTION
**Pull request by jacknagz**
### Background

- Detects when a known bad IP is getting/listing objects from S3 using CloudTrail
- We can also write a version of this rule on S3 Access Logs

### Changes

* Add a new rule to detect AWS S3 Get/List Object with tests

### Testing

* Local unit testing + baking in a test instance

### CODE REVIEW

**Comment by jacknagz** [comment]
sup @k-bailey @bseb

**Review by k-bailey — APPROVED** [review]

**Comment by k-bailey** [comment]
@jacknagz it looks like there were some linting failures, I'll handle them tomorrow morning and let you know when it is good to merge.

**Review by k-bailey — APPROVED** [review]

**Comment by k-bailey** [comment]
@jacknagz you're good to merge.

**Comment by jacknagz** [comment]
I can't merge bc I"m not in the CLA bot - can somebody pls fix that? @k-bailey @bseb

**Pull request merged**
