### PR TITLE
Remove managed schemas

### PR DESCRIPTION
**Pull request by georgepsarakis**
### Background

Relates to https://app.asana.com/0/1200908948600021/1202130294162121

### Changes

- Remove codeowner
- Remove Managed Schema YAML files
- Remove associated CI commands for schema testing and linting
- Remove associated Makefile commands for publishing a new distribution

### Testing

* N/A

### CODE REVIEW

**Comment by giorgosp** [comment]
Would be nice to have more context about the motivation in the PRs description. Mostly for historical reasons and for some of us that just got back from PTO :D

**Comment by georgepsarakis** [comment]
We are still running some final checks so feel free to review, but let's hold on merging until further notice.

**Comment by alxarch** [comment]
After walking through the code on `panther-enterprise` I think it is safe to proceed with this. We should also remove the mage schemas:sync task to prevent anyone from overwriting the YAML files on `panther-enterprise`.

**Review by papanikge — APPROVED** [review]

**Comment by papanikge** [comment]
@nhakmiller and/or @panther-labs/detections and/or @panther-labs/security can we get an approve here?
We're moving forward with the removal of the legacy syncing-pipeline and the schemas in this repo.

**Review by edyesed — APPROVED** [review]
Additional context on this change, and explanations around already-in-place mitigation for the removed files was provided via internal company chat. This change is good to ship :shipit:

**Pull request merged**
