### PR TITLE
Added Lacework compliance

### PR DESCRIPTION
**Pull request by kostaspap**
### Background

Added Lacework Cloud compliance schema

### Changes

* Added Lacework cloud compliance schema

### Testing

* `./pantherlog test ./schemas/logs/lacework`

(note that CLI is failing but this seems too be the case for all open PRs)

### CODE REVIEW

**Comment by nhakmiller** [comment]
The schema tests have been failing since @alxarch merged this https://github.com/panther-labs/panther-analysis/pull/247 PR. I asked him about it somewhere in a comment thread on GitHub, but I'm guessing it got buried. Could you check with him on getting these tests passing?

**Comment by kostaspap** [comment]
> The schema tests have been failing since @alxarch merged this #247 PR. I asked him about it somewhere in a comment thread on GitHub, but I'm guessing it got buried. Could you check with him on getting these tests passing?

It's being worked on currently, should be fixed soon: https://app.asana.com/0/1200175800812961/1200178230343867

**Review by jpl5280 — APPROVED** [review]

**Review by alxarch — APPROVED** [review]
LGTM
Since we do not have such an automated test yet, can you try to use pantherlog parse with wrong samples to verify there are no conflicts?
For example can you run AlertDetails samples agains CloudCompliance schema?

**Comment by kostaspap** [comment]
> LGTM
> Since we do not have such an automated test yet, can you try to use pantherlog parse with wrong samples to verify there are no conflicts?
> For example can you run AlertDetails samples agains CloudCompliance schema?

Tested and yes, there were no conflicts (all AlertDetails samples were failing classification when using CloudCompliance parser and vv). Also double-checked and this is expected from the schemas: `Lacework.CloudCompliance` has a required `ACCOUNT` field not present in the `Lacework.AlertDetails`, while `Lacework.AlertDetails` has a required field `ENTITY_MAP` not present in CloudCompliance.

**Pull request merged**
