### PR TITLE
Set severity to INFO if making calendar private

### PR DESCRIPTION
**Pull request by apanzerj**
https://developers.google.com/admin-sdk/reports/v1/appendix/activity/calendar#change_calendar_acls

None means nobody can see your calendar. This should just be info level.

### Background

When changing a calendar from freebusy to say 'none' it should only be INFO severity.

### Changes

Change severity based on access change

### Testing

Is there a way to test for severity?

### CODE REVIEW

**Comment by arielkr256** [comment]
@apanzerj this change makes sense to me.  Yes, it is possible to test for severity.  You would need to duplicate the true positive test case in gsuite_calendar_made_public.yml and set `parameters.access_level` to `'none'`

**Comment by apanzerj** [comment]
How do I test for the severity though? 

All I see is ExpectedResult

Is it ExpectedSeverity?

**Comment by arielkr256** [comment]
Ah gotcha.  No, there is nothing to add in the YAML for expected severity, it would show up in the PAT debug log when you run the tests, something like:

[PASS] User Publically Shared a Calendar
                [PASS] [rule] true
                [PASS] [severity] MEDIUM
[PASS] User set calendar or event not visible
                [PASS] [rule] true
                [PASS] [severity] LOW

**Comment by apanzerj** [comment]
@arielkr256 added a test case

**Comment by arielkr256** [comment]
Please run `make fmt`, `make lint`, and `make test` in PAT to resolve any formatting and linter issues.  Otherwise looks great!

**Comment by apanzerj** [comment]
@arielkr256 `make fmt` adds spurious changes from the nontion_rules folder that aren't mine. 

```diff
diff --git a/rules/notion_rules/notion_account_changed_after_login.py b/rules/notion_rules/notion_account_changed_after_login.py
index 53fd4e6..daec345 100644
--- a/rules/notion_rules/notion_account_changed_after_login.py
+++ b/rules/notion_rules/notion_account_changed_after_login.py
@@ -1,9 +1,9 @@
 import time
+
 from global_filter_notion import filter_include_event
 from panther_notion_helpers import notion_alert_context
 from panther_oss_helpers import get_string_set, put_string_set

-
 # Length of time in minutes. If a user logs in, then changes their email within this many
 # minutes, raise an alert.
 DEFAULT_EMAIL_CHANGE_WINDOW_MINUTES = 10
diff --git a/rules/notion_rules/notion_login_from_new_location.py b/rules/notion_rules/notion_login_from_new_location.py
index 07b2a64..5dec29c 100644
--- a/rules/notion_rules/notion_login_from_new_location.py
+++ b/rules/notion_rules/notion_login_from_new_location.py
@@ -1,11 +1,11 @@
 import datetime
-import time
 import json
+import time

 from global_filter_notion import filter_include_event
+from panther_ipinfo_helpers import IPInfoLocation
 from panther_notion_helpers import notion_alert_context
 from panther_oss_helpers import get_dictionary, put_dictionary
-from panther_ipinfo_helpers import IPInfoLocation

 # How long (in seconds) to keep previous login locations in cached memory
 DEFAULT_CACHE_PERIOD = 2419200
diff --git a/rules/notion_rules/notion_page_accessible_to_guests.py b/rules/notion_rules/notion_page_accessible_to_guests.py
index eb2db4e..89c1533 100644
--- a/rules/notion_rules/notion_page_accessible_to_guests.py
+++ b/rules/notion_rules/notion_page_accessible_to_guests.py
@@ -1,6 +1,6 @@
 from global_filter_notion import filter_include_event
-from panther_notion_helpers import notion_alert_context
 from panther_base_helpers import deep_get
+from panther_notion_helpers import notion_alert_context

 # These event types correspond to users adding or editing the default role on a public page
 event_types = ("page.permissions.guest_role_added", "page.permissions.guest_role_updated")
 ```

**Comment by apanzerj** [comment]
Should I add them in?

**Comment by arielkr256** [comment]
No, just commit changes to the Google calendar rule you modified.  I will try to cleanup some of the lingering formatting issues in other rules.

**Review by arielkr256 — APPROVED** [review]
Rule modification and new test looks good

**Comment by arielkr256** [comment]
@apanzerj  this is good to go and will auto-merge as soon as you update your branch

**Comment by apanzerj** [comment]
Whoops! Updating.

**Pull request merged**
