### PR TITLE
Tines Rule - Team Destruction

### PR DESCRIPTION
**Pull request by josh-panther**
### Background

https://www.tines.com/api/audit-logs#:~:text=team%20was%20created-,TeamDestruction,-A%20team%20was

### Changes

* Tines - TeamDestruction rule

### Testing

```
Tines.Team.Destruction
	[PASS] Detection Trigger
		[PASS] [rule] true
		[PASS] [title] Tines [TeamDestruction] performed by [user@email.com] on [tines-log-source-name].
		[PASS] [dedup] Tines [TeamDestruction] performed by [user@email.com] on [tines-log-source-name].
		[PASS] [alertContext] {"actor": "user@email.com", "action": "TeamDestruction", "tenant_id": "1337", "user_email": "user@email.com", "user_id": "7331", "operation_name": "TeamDestruction", "request_ip": "98.224.225.84"}
	[PASS] Tines Login
		[PASS] [rule] false
```

### CODE REVIEW

**Comment by andrea-youwakim** [comment]
failing lint and test

**Review by andrea-youwakim — CHANGES_REQUESTED** [review]
please add at least one more test case - that covers an outcome where we shouldn't alert, thanks

**Review by edyesed — CHANGES_REQUESTED** [review]
same feedback around the globals and using deep_get in place of `event.get()` as in #788

**Comment by josh-panther** [comment]
Waiting for https://github.com/panther-labs/panther-analysis/pull/786 before review req

**Review by edyesed — APPROVED** [review]
adds a LOW severity alert for Tines audit log TeamDestruction event

**Pull request merged**
