### PR TITLE
chore: double-check revert of 498 and 504

### PR DESCRIPTION
**Pull request by edyesed**
### Background

<High level overview here>

### Changes

* <Describe changes here>

### Testing

* <Testing steps>

### CODE REVIEW

**Review by darwayne — APPROVED** [review]

**Comment by darwayne** [comment]
woah, lots of conflicts

**Comment by darwayne** [comment]
did you mean to merge this to master?

**Comment by edyesed** [comment]
> 

I intended to PR against the revert branch. I was curious how this would fair against the revert branch. I checked the files out at 5e9165bf6afccb8a0dbce1abefbc5f9c794db9c1

**Comment by edyesed** [comment]
this was for comparison's sake. closing now that comparison is over

**Pull request closed without merging**
