### PR TITLE
`deep_get` helper enhancements & unit tests for global helpers

### PR DESCRIPTION
**Pull request by georgepsarakis**
### Background

The new version is about 10% faster in successful lookups, and approximately 2.5x faster for the case where the first key is absent. Benchmarks were performed on a dictionary with 3 keys as input.

Since we are changing the behavior compared to the previous implementation, we still maintain the legacy version, in case a detection relies on it and a patch is required.

We are also introducing unit tests for global helpers as part of the CI process.

### Changes

* Rename existing `deep_get` function to `deep_get_legacy` to allow potential patches.
* Implement a new version of `deep_get` that can be slightly more performant and potentially easier to comprehend.
* Introduce unit tests for global helpers. We treat `global_helpers/*.py` as Python modules and allow them to be importable by appending their path to the import paths list (`sys.path`). Note that the import names are not the global helper names as defined in the accompanying YAML metadata files, but the filename itself.

### Testing

* Added unit tests in CI

### CODE REVIEW

**Comment by glerb** [comment]
If the output is the same, we shouldn't need to maintain the legacy version, right? Isn't that one of the main benefits of object oriented programming? That you can swap out implementations as long as the interface remains the same?

**Review by lindsey-w — DISMISSED** [review]
wow, that's a significant improvement

**Review by bseb — APPROVED** [review]
Very nice!

**Comment by georgepsarakis** [comment]
Closing and may possibly resume work on this at a later time. @bseb the global helpers unit testing approach may be worth considering though.

**Pull request closed without merging**
