### PR TITLE
Add YAML and Markdown formatting

### PR DESCRIPTION
**Pull request by le4ker**
### Background

Adds [prettier](https://prettier.io/) formatter to the repository in order to format YAML and Markdown files

Prettier will be installed after running `make install` and then the YAML and Markdown files can be formatted by running `make fmt`:

### Testing

```bash
make install
make fmt
```

Needs [this](https://github.com/panther-labs/panther_analysis_tool/pull/470) PAT update to run the tests successfully.

### CODE REVIEW

**Review by kjihso — APPROVED** [review]
This looks great, @le4ker !

Thanks for getting a hygiene improving solution in place.

**Review by arielkr256 — APPROVED** [review]

**Review by egibs — APPROVED** [review]

**Comment by kjihso** [comment]
@le4ker , @egibs 

Does pat need to be updated to ignore ```package-lock.json```? I'm getting the following with make test and I see it in the test failure log here on the pr merge to release as well:

```
  Invalid Tests Summary
  	/home/runner/work/panther-analysis/panther-analysis/package-lock.json
  		Missing key: 'AnalysisType'
  
  	/home/runner/work/panther-analysis/panther-analysis/package.json
  		Missing key: 'AnalysisType'
```

https://github.com/panther-labs/panther-analysis/actions/runs/8422896110/job/23063255413

**Comment by kjihso** [comment]
lol, should have looked at pat, first. It looks like this depends on: https://github.com/panther-labs/panther_analysis_tool/pull/470/files

**Comment by le4ker** [comment]
> lol, should have looked at pat, first. It looks like this depends on: https://github.com/panther-labs/panther_analysis_tool/pull/470/files

@kjihso correct, I have it mentioned in the PR description as well 😄 

> Needs https://github.com/panther-labs/panther_analysis_tool/pull/470 PAT update to run the tests successfully.

**Pull request merged**
