### PR TITLE
Add back Tor Exit Nodes LUT now that 1.45 is released

### PR DESCRIPTION
**Pull request by rleighton**
### Background

Add back Tor Exit Nodes LUT now that 1.45 is released

image

### Changes

* Add LUT tor_exit_nodes.yml
* Add pack tor.yml

### Testing

* Loaded via UI

### CODE REVIEW

**Comment by darwayne** [comment]
Would like to get sign off from @panther-labs/security and @lindsey-w  before we merge this in

**Comment by edyesed** [comment]
FYI: internal discussion is happening on this. @rleighton

**Review by edyesed — CHANGES_REQUESTED** [review]
Placing a hold on this PR while sorting the version dependency

**Comment by rleighton** [comment]
What's the plan / time table?

**Comment by rleighton** [comment]
@edyesed Can this be merged now?

**Review by lindsey-w — APPROVED** [review]

**Comment by rleighton** [comment]
@edyesed Can this be merged now?

**Review by edyesed — APPROVED** [review]

**Pull request merged**
